apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  image: chinwendu20/otel-custom
  config: |
    receivers:
      kubearmor_receiver:
        endpoint: :32767
        logfilter: all
    
    exporters:
      file:
        path: ./output.log
    
    service:
      pipelines:
        logs:
          receivers:
            - kubearmor_receiver
          processors: []
          exporters:
            - file
