apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  image: chinwendu20/receiver
  config: |
    receivers:
      kubearmor_receiver:
        logfilter: all
    
    exporters:
      file:
        path: ./output.log
    
    service:
      pipelines:
        logs:
          receivers:
            - kubearmor_receiver
          processors: []
          exporters:
            - file
  env:
  - name: KUBEARMOR_SERVICE
    value: kubearmor.kube-system.svc:32767
