receivers:
  kubearmor_receiver:
    endpoint: :32767
    logfilter: system

exporters:
  file:
    path: ./output.log

service:
  pipelines:
    logs:
      receivers:
        - kubearmor_receiver
      processors: []
      exporters:
        - file