receivers:
  kubearmor_receiver:
    endpoint: :32767
    logfilter: all

exporters:
  file:
    path: ./output.log


service:
  pipelines:
    logs:
      receivers:
        - kubearmor_receiver
      processors: []
      exporters:
        - splunk_hec
        - file
